# Merged Pull Request
#
# Pull Request가 Merge되는 시점에 수행됩니다.
name: Merged Pull Request

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - feature/*

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

      # master 브랜치로 merge된 경우 태깅 처리를 진행합니다.
      - name: Git Tagging
        if: ${{ github.base_ref == 'master' }}
        run: |
          git tag -a '#${{ github.event.pull_request.number }}' ${{ github.event.pull_request.merge_commit_sha }} -m '#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
          git push origin '#${{ github.event.pull_request.number }}'

      # merge된 소스 브랜치를 리모트에서 삭제합니다.
      - name: Delete remote branch
        if: ${{ success() }}
        run: |
          echo "delete head_ref: ${{ github.head_ref }}"
          EXISTED=$(git ls-remote --heads origin ${{ github.head_ref }})

          if [[ -z ${EXISTED} ]]; then
            echo "branch do not exist"
          else
            git push origin --delete ${{ github.head_ref }}
          fi
